#!/bin/sh
exec 2>&1
SCRIPT_DIR=$(cd "$(dirname "$(readlink -f "$0")")/.." && pwd)
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}"  )" &> /dev/null && pwd  )
python "$SCRIPT_DIR/dbus-homewizard-energy-p1.py"
